// Generated by ORVOX. Do not edit.

export const server = Bun.serve({
  hostname: process.env.HOST ?? "127.0.0.1",
  port: Number(process.env.PORT ?? 3000),
  development: false,
  maxRequestBodySize: 1048576,
  error() {
    return new Response("Internal Server Error", { status: 500 });
  },

  routes: {
    "/": {
      GET: new Response("hello"),
    },
    "/users/:id": {
      GET(req) {
        const params = req.params;
        return Response.json({ id: params.id });
      },
    },
  },
  fetch(req) {
    const path = new URL(req.url).pathname;
    if (path === "/") {
      const allow = "GET, HEAD, OPTIONS";
      if (req.method === "OPTIONS") {
        return new Response(null, { status: 204, headers: { allow } });
      }
      return new Response("Method Not Allowed", {
        status: 405,
        headers: { allow },
      });
    }
    if (/^\/users\/[^/]+$/.test(path)) {
      const allow = "GET, HEAD, OPTIONS";
      if (req.method === "OPTIONS") {
        return new Response(null, { status: 204, headers: { allow } });
      }
      return new Response("Method Not Allowed", {
        status: 405,
        headers: { allow },
      });
    }
    return new Response("Not Found", { status: 404 });
  },
});

if (import.meta.main) {
  console.log(`ORVOX listening on ${server.url}`);
  let __orvoxStopping = false;
  const __orvoxShutdown = async () => {
    if (__orvoxStopping) return;
    __orvoxStopping = true;
    await server.stop();
  };
  process.once("SIGINT", __orvoxShutdown);
  process.once("SIGTERM", __orvoxShutdown);
}
